import turtle

window = turtle.Screen()  # Set up the window and its attributes
window.bgcolor("lightgreen")

# TMNT - turtles
# create a turtle called mikey
mikey = turtle.Turtle()
mikey.turtlesize(0.5)  # size
mikey.color("white")  # colour
mikey.shape("turtle")
mikey.speed(12)
mikey.width(5)
mikey.penup()
mikey.left(90)
mikey.forward(200)
mikey.right(90)
mikey.pendown()
mikey.begin_fill()
mikey.circle(100)
mikey.end_fill()
mikey.right(90)
mikey.forward(250)
mikey.left(90)
mikey.begin_fill()
mikey.circle(150)
mikey.end_fill()
mikey.right(90)
mikey.forward(250)
mikey.left(90)
mikey.begin_fill()
mikey.circle(200)
mikey.end_fill()
mikey.left(90)
mikey.penup()
mikey.color("black")
mikey.forward(595)
mikey.left(90)
mikey.forward(50)
mikey.right(180)
mikey.begin_fill()
mikey.circle(15)
mikey.end_fill()
mikey.forward(100)
mikey.begin_fill()
mikey.circle(15)
mikey.end_fill()
mikey.penup()
mikey.backward(50)
mikey.color("orange")
mikey.pendown()
mikey.right(60)
mikey.begin_fill()
mikey.forward(20)
mikey.right(120)
mikey.forward(20)
mikey.right(120)
mikey.forward(20)
mikey.end_fill()
mikey.penup()
mikey.right(150)
mikey.forward(50)
mikey.left(90)
mikey.color("black")
mikey.pendown()
mikey.forward(50)
mikey.backward(100)
mikey.forward(50)
mikey.pu()
mikey.right(90)
mikey.forward(100)
mikey.left(90)
for circles in range(3):
    mikey.pendown()
    mikey.begin_fill()
    mikey.circle(10)
    mikey.end_fill()
    mikey.penup()
    mikey.right(90)
    mikey.forward(75)
    mikey.left(90)
mikey.penup()
mikey.right(90)
mikey.backward(250)
mikey.color("brown")
mikey.width(7)
mikey.right(90)
mikey.forward(100)
mikey.left(70)
mikey.pd()
mikey.forward(200)
mikey.backward(200)
mikey.pu()
mikey.left(110)
mikey.forward(200)
mikey.right(70)
mikey.pd()
mikey.forward(200)


## Functions and Turtles

window.exitonclick()
